# Generated by Django 5.1.1 on 2024-09-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('inteviewer', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='')),
                ('experience', models.TextField()),
                ('address', models.TextField()),
                ('tech_stack', models.TextField()),
            ],
        ),
    ]
