# Generated by Django 5.1.1 on 2024-10-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='ta_member_id',
            new_name='ta_member',
        ),
    ]
