# Generated by Django 5.1.1 on 2024-10-16 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment_portal.interviewer'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='poc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment_portal.poc'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ta_member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment_portal.tamember'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment_portal.team'),
        ),
    ]
