# Generated by Django 5.1.1 on 2024-12-26 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('ldap', models.CharField(max_length=255)),
                ('lead', models.CharField(max_length=255)),
                ('process', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=20)),
                ('time_in_mins', models.IntegerField()),
                ('comment', models.TextField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment_portal.program')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment_portal.team')),
            ],
        ),
    ]
