# Generated by Django 5.1.1 on 2024-09-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_portal', '0002_remove_candidate_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='inteviewer',
            new_name='interviewer',
        ),
    ]
