# Generated by Django 5.1.1 on 2024-11-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_portal', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_set_password',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('POC', 'POC'), ('TA_Manager', 'TA Manager'), ('Team_Manager', 'Team Manager'), ('TA_Member', 'TA Member'), ('Team_Member', 'Team Member')], default='Team_Member', max_length=20),
        ),
    ]
