# Generated by Django 5.1.1 on 2024-10-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_portal', '0002_alter_candidate_interviewer_alter_candidate_poc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='interviewer',
        ),
    ]
