# Generated by Django 5.1.1 on 2024-09-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_portal', '0003_rename_inteviewer_candidate_interviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default='none', upload_to=''),
        ),
    ]
