# Generated by Django 5.1.1 on 2024-09-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_portal', '0003_remove_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
