# Generated by Django 5.1.1 on 2024-11-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_portal', '0004_alter_tateam_ta_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tateam',
            name='ta_team_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
