# Generated by Django 5.1.1 on 2024-09-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_portal', '0004_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='firstround',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='registerdate',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='secondround',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
