# Generated by Django 5.1.1 on 2024-11-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_portal', '0005_alter_tateam_ta_team_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
