# Generated by Django 5.1.1 on 2024-10-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_portal', '0005_candidate_firstround_candidate_registerdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='firstround',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='secondround',
        ),
    ]
